// Generated by CoffeeScript 1.10.0
(function() {
  var manager, tableauJours;

  tableauJours = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"];

  window.enTrainDeDrag = false;

  window.dragged = null;

  console.log("init");

  manager = new window.CreneauManager();

  $(document).ready(function() {
    var classPlacer, createur, i, jour, len, tableau;
    createur = new window.PlanningHtmlCreator(salles, 8, 22);
    classPlacer = new window.ClassPlacer();
    tableau = createur.creerTableauJour;
    classPlacer.placerDropZones(tableau);
    for (i = 0, len = tableauJours.length; i < len; i++) {
      jour = tableauJours[i];
      $("#" + jour).append(tableau);
    }
    classPlacer.placerClassePlanning();
    $("#edt").tabs();
    $(document).tooltip();
    if (enModif === true) {
      console.log("je suis en modif");
      $("#addCreneau").click(function() {
        var crPlaI, form;
        form = $("#ajoutCreneau");
        crPlaI = $("#creneauxPlacement i");
        if (form.css("display") === "none") {
          form.slideDown();
          crPlaI.removeClass('fa-plus-square');
          return crPlaI.addClass('fa-minus-square');
        } else {
          form.slideUp();
          crPlaI.addClass('fa-plus-square');
          return crPlaI.removeClass('fa-minus-square');
        }
      });
      window.makeDroppableOnglets($("#jours li"));
      window.creerZonesDroppables();
    }
    return manager.placerCreneaux(creneauxJS, enModif);
  });

}).call(this);
