package fr.gemao.view;

public class Pattern {
	public final static String
		// Module
		MODULE_ADHERENT = "/Adherent",
		MODULE_ADMINISTRATION = "/Administration",
		MODULE_LOCATION = "/Location",
		MODULE_MATERIEL = "/Materiel",
		MODULE_PERSONNEL = "/Personnel",
		MODULE_COURS = "/Cours",
		MODULE_PLANNING = "/Planning",
		MODULE_COMPTABILITE_ENSEIGNEMENT="/ComptabiliteEnseignement",

		// Droit
		DROIT_ECRITURE = "-w",

		// Divers
		ACCUEIL = "/",
		CHANGER_MOT_DE_PASSE = "/ChangerMotDePasse",
		CONFIGURATION = "/Configuration",
		CONNEXION = "/Connexion",
		DECONNEXION = "/Deconnexion",

		// Module adhérent
		ADHERENT_AJOUT = MODULE_ADHERENT + DROIT_ECRITURE + "/AjoutAdherent",
		ADHERENT_AJOUT_RESPONSABLE = MODULE_ADHERENT + DROIT_ECRITURE + "/AjoutResponsable",
		ADHERENT_CALCUL_QF = MODULE_ADHERENT + DROIT_ECRITURE + "/CalculerQF",
		ADHERENT_SIMPLE_CALCUL_QF = MODULE_ADHERENT + "/SimpleCalculerQF",
		ADHERENT_CONSULTER = MODULE_ADHERENT + "/ConsulteAdherent",
		ADHERENT_LISTER = MODULE_ADHERENT + "/ListeAdherents",
		ADHERENT_LISTER_ANCIEN = MODULE_ADHERENT + "/ListeAnciensAdherents",
		ADHERENT_MODIFIER = MODULE_ADHERENT + DROIT_ECRITURE + "/ModifierAdherent",
		ADHERENT_DESINSCRIRE = MODULE_ADHERENT + DROIT_ECRITURE + "/DesinscrireAdherent",
		ADHERENT_PARAMETRE = MODULE_ADHERENT + DROIT_ECRITURE + "/Parametres",
		ADHERENT_VALIDATION_AJOUT = MODULE_ADHERENT + "/ValidationAjoutAdherent",
		ADHERENT_VALIDATION_MODIF = MODULE_ADHERENT + "/ValidationModifAdherent",
		ADHERENT_SAISIE_COTISATION = MODULE_ADHERENT + DROIT_ECRITURE + "/SaisieCotisation",
		ADHERENT_EXPORTER = MODULE_ADHERENT + "/exporter",
		ADHERENT_EXPORTER_ANCIENS = MODULE_ADHERENT + "/exporterAnciens",
		ADHERENT_LISTE_DISCIPLINES = MODULE_ADHERENT + "/ListeDisciplines",
		ADHERENT_APAYE = MODULE_ADHERENT + "/APaye",
		ADHERENT_REINIT_APAYE = MODULE_ADHERENT + "/ReinitAPaye",
		ADHERENT_REINSCRIRE = MODULE_ADHERENT + "/Reinscrire",
		ADHERENT_VALIDATION_REINS = MODULE_ADHERENT + "/ValidationReinsAdherent",
		ADHERENT_MODIFER_QF = MODULE_ADHERENT + "/ModifierQF",

		TEST = MODULE_ADHERENT + "/test",

		// Module administration
		ADMINISTRATION_RESET_PASSWORD = MODULE_ADMINISTRATION + DROIT_ECRITURE + "/ReinitMotDePasse",
		ADMINISTRATION_AJOUT_PROFIL = MODULE_ADMINISTRATION + DROIT_ECRITURE + "/AjouterProfil",
		ADMINISTRATION_CHANGER_PROFIL = MODULE_ADMINISTRATION + DROIT_ECRITURE + "/ChangerProfil",
		ADMINISTRATION_CONSULTER_PROFIL = MODULE_ADMINISTRATION + "/ConsulterProfil",
		ADMINISTRATION_LISTER_MODIFICATION = MODULE_ADMINISTRATION + "/ListerModifications",
		ADMINISTRATION_LISTER_PROFIL = MODULE_ADMINISTRATION + "/ListerProfils",
		ADMINISTRATION_MODIF_EXPORTER = MODULE_ADMINISTRATION + "/ExporterModifs",
		ADMINISTRATION_MODIFIER_PROFIL = MODULE_ADMINISTRATION + DROIT_ECRITURE + "/ModifierProfil",
		ADMINISTRATION_SUPPRIMER_PROFIL = MODULE_ADMINISTRATION + DROIT_ECRITURE + "/SupprimerProfil",

		// Module location
		LOCATION_LOCATION_INTERNE = MODULE_LOCATION + DROIT_ECRITURE + "/locationInterne",
		LOCATION_LOCATION_EXTERNE = MODULE_LOCATION + DROIT_ECRITURE + "/LocationExterne",
		LOCATION_RETOUR = MODULE_LOCATION + DROIT_ECRITURE + "/retourInstrument",
		LOCATION_LISTER = MODULE_LOCATION + DROIT_ECRITURE + "/listerLocations",
		LOCATION_IMPRIMER = MODULE_LOCATION + DROIT_ECRITURE + "/imprimLocation",
		LOCATION_CONTRAT_LISTER = MODULE_LOCATION + DROIT_ECRITURE + "/listerContratsLocation", 

		// Module matériel
		MATERIEL_AJOUT = MODULE_MATERIEL + DROIT_ECRITURE + "/AjouterMateriel",
		MATERIEL_CONSULTER = MODULE_MATERIEL + "/ConsulterMateriel",
		MATERIEL_LISTER = MODULE_MATERIEL + "/ListerMateriel",
		MATERIEL_MODIFIER = MODULE_MATERIEL + DROIT_ECRITURE + "/ModifierMateriel",
		MATERIEL_EXPORTER = MODULE_MATERIEL + "/Exporter",
		MATERIEL_LISTE_ETAT = MODULE_MATERIEL + DROIT_ECRITURE + "/ListerEtat",
		MATERIEL_LISTE_CATEGORIE = MODULE_MATERIEL + DROIT_ECRITURE + "/ListerCategorie",
		MATERIEL_LISTE_FOURNISSEUR = MODULE_MATERIEL + DROIT_ECRITURE + "/ListerFournisseur",
		MATERIEL_LISTE_MARQUE = MODULE_MATERIEL + DROIT_ECRITURE + "/ListerMarque",
		MATERIEL_LISTE_DESIGNATION = MODULE_MATERIEL + DROIT_ECRITURE + "/ListerDesignation",

		// Module personnel
		PERSONNEL_AJOUT = MODULE_PERSONNEL + DROIT_ECRITURE + "/AjoutPersonnel",
		PERSONNEL_AJOUT2 = MODULE_PERSONNEL + DROIT_ECRITURE + "/AjoutPersonnel2",
		PERSONNEL_VALIDATION_MODIF = MODULE_PERSONNEL + "/ValidationModifPersonnel",
		PERSONNEL_VALIDATION_AJOUT = MODULE_PERSONNEL + "/ValidationAjoutPersonnel",
		PERSONNEL_CONSULTER = MODULE_PERSONNEL + "/ConsulterPersonnel",
		PERSONNEL_LISTER = MODULE_PERSONNEL + "/ListePersonnel",
		PERSONNEL_MODIFIER = MODULE_PERSONNEL + DROIT_ECRITURE + "/ModifPersonnel",
		PERSONNEL_EXPORTER = MODULE_PERSONNEL + "/Exporter",

		// Module Cours
		COURS_AJOUTEDT = "/cours/AjouterEmploiDuTemps",
		
		//Module comptabilité enseignement
		COMPTABILITE_ENSEIGNEMENT = MODULE_COMPTABILITE_ENSEIGNEMENT + DROIT_ECRITURE + "ComptabiliteEnseignement",

		// Module Planning
		PLANNING_AFFICHER = MODULE_PLANNING + "/AfficherPlanning",
		PLANNING_LISTER = MODULE_PLANNING + "/ListerPlannings",
		PLANNING_LISTER_ARCHIVE = MODULE_PLANNING + "/ListerPlanningArchive",
		PLANNING_CREER = MODULE_PLANNING + "/CreerPlanning",
		PLANNING_ARCHIVER = MODULE_PLANNING + "/ArchiverPlanning",
		CRENEAU_MODIFIER = MODULE_PLANNING + "/ModifierCreneau",
		PLANNING_MODIFIERCRENEAUX = MODULE_PLANNING + "/ModifierCreneauxPlanning",
		RESERVATION_LISTER = MODULE_PLANNING + "/ListerReservations",
		RESERVATION_CREER = MODULE_PLANNING + "/CreerReservation",
		CRENEAUX_LISTER = MODULE_PLANNING + "/ListerCreneaux",
		PLANNING_MODIFIER_CARACTERISTIQUES = MODULE_PLANNING + "/ModifierCaracteristiquesPlanning",
		CRENEAU_CREER = MODULE_PLANNING + "/CreerCreneau",
		CRENEAU_SUPPRIMER = MODULE_PLANNING + "/SupprimerCreneau",
		SALLE_LISTER = MODULE_PLANNING + "/ListerSalle",
		SALLE_CREER = MODULE_PLANNING + "/CreerSalle",
		SALLE_MODIFIER = MODULE_PLANNING + "/ModifierSalle",
		COURS_LISTER = MODULE_PLANNING + "/ListerCours",
		COURS_CREER = MODULE_PLANNING + "/CreerCours",
		CONTRAINTE_MODIFIER = MODULE_PLANNING + "/ModifierContrainte",
		CONTRAINTE_ADD_GLOBALE = MODULE_PLANNING  + "/ContrainteGlobale",
		CONTRAINTE_LISTE_GLOBALE = MODULE_PLANNING + "/ListerContrainteGlobale",
		COURS_MODIFIER = MODULE_PLANNING + "/ModifierCours";
}
